#' Generate GSEA Plots and Save Results
#'
#' This function generates various plots based on Gene Set Enrichment Analysis (GSEA) results, including bar plots, enrichment plots, network plots, and heatmaps. It also saves the GSEA results and writes them to CSV files for further analysis.
#'
#' @param ewp2 An object containing GSEA results, typically generated by the `clusterProfiler::GSEA` function.
#' @param Prefix A string used as a prefix for output file names and plot titles.
#' @param contraste A string specifying the contrast or condition being analyzed. This is used in output file names and plot titles.
#' @param DataBase A string specifying the database used for GSEA (e.g., "WikiPathways", "MSigDB").
#' @param geneList A named numeric vector representing the gene list used for GSEA. The names should correspond to gene identifiers, and the values should represent the ranking metric (e.g., log fold change or statistical significance).
#'
#' @return This function generates and saves plots as PDF files and writes GSEA results to CSV files. It does not return any R objects directly.
#' @export
#'
#' @examples
#' # Example usage:
#' # Assuming `ewp2` is a GSEA result object, `Prefix` is "Experiment1",
#' # `contraste` is "ConditionA", `DataBase` is "WikiPathways", and `geneList` is a named numeric vector:
#' ClusterProfilerPlots(ewp2, "Experiment1", "ConditionA", "WikiPathways", geneList)
#'
ClusterProfilerPlots <- function(ewp2, Prefix, contraste, DataBase, geneList) {
  # Aesthetic adjustments for network plots
  aescnet <- function(g) {
    g$layers[[3]]$aes_params$size = 2
    return(g)
  }

  # Save GSEA results and write to CSV
  saveRDS(ewp2, paste(DataBase, Prefix, contraste, "GSEA.Rdata", sep = "_"))
  fgseaRes = ewp2@result
  write.csv(fgseaRes, paste(Prefix, contraste, DataBase, "GSEATable.csv", sep = "_"))

  # Filter and tidy GSEA results
  fgseaRes = fgseaRes %>% 
    dplyr::arrange(pvalue) %>% 
    tibble::as_tibble() %>%
    dplyr::filter(p.adjust < 0.2) %>% 
    dplyr::mutate(Sign = paste("Sign", sign(NES)) ) %>% 
    dplyr::arrange(desc(NES))

  fgseaResTidy = tidyGSEA(fgseaRes)

  # Bar plot
  pdf(paste(DataBase, Prefix, contraste, "GSEA.pdf", sep = "_"), width = 12)
  print(
    ggpubr::ggbarplot(
      fgseaResTidy, 
      x = "Description", 
      y = "NES",
      fill = "Sign",           # Change fill color by NES sign
      color = "white",         # Set bar border colors to white
      palette = c("navy", "firebrick"),  
      sort.val = "asc",        # Sort values in ascending order
      sort.by.groups = FALSE,  # Don't sort inside each group
      x.text.angle = 90,       # Rotate x-axis text vertically
      ylab = "Normalized Enrichment Score",
      xlab = "Description",
      rotate = TRUE,
      ggtheme = theme_minimal()
    ) +
      theme(legend.position = "none")
  )
  dev.off()

  # Top negative and positive GSEA pathways
  y1 = fgseaRes %>% filter(qvalue < 0.2) %>% filter(NES < 0) %>% arrange(desc(abs(NES)))
  y2 = fgseaRes %>% filter(qvalue < 0.2) %>% filter(NES > 0) %>% arrange(desc(abs(NES)))

  # Negative pathways plot
  pdf(paste(DataBase, Prefix, contraste, "NegtopGSEA.pdf", sep = "_"))
  print(
    try(enrichplot::gseaplot2(
      ewp2, 
      geneSetID = y1$ID[1:4], 
      subplots = 1:2, 
      pvalue_table = TRUE, 
      color = c("#ED574EFF", "firebrick", "#FF7F00", "gold")
    ), silent = TRUE)
  )
  dev.off()

  # Positive pathways plot
  pdf(paste(DataBase, Prefix, contraste, "PostopGSEA.pdf", sep = "_"))
  print(
    try(enrichplot::gseaplot2(
      ewp2, 
      geneSetID = y2$ID[1:4], 
      subplots = 1:2, 
      pvalue_table = TRUE, 
      color = c("royalblue", "gray", "#6F9DC4FF", "navy")
    ), silent = TRUE)
  )
  dev.off()

  # Network plot
  g = try(cnetplot(ewp2, foldChange = geneList, colorEdge = TRUE, showCategory = 4), silent = TRUE)
  pdf(paste(DataBase, Prefix, contraste, "EnrichNetWork.pdf", sep = "_"), width = 18, height = 18)
  print(
    g + theme(legend.position = "none")
  )
  dev.off()

  # Heatmap plot
  pdf(paste(DataBase, Prefix, contraste, "heatmap.pdf", sep = "_"), width = 30)
  print(
    enrichplot::heatplot(ewp2, foldChange = geneList, showCategory = 5)
  )
  dev.off()
}